### ISSUE TITLE
config.phコピー時にエラー

### ISSUE THREAD

**Issue by ghost** [fumiyas/mailman-hack#1]
実行してみました。
319行目の下記部分でエラーになりますね。

run cp -pn config.ph "$tmp_dir"/* "$mm_fml_dir/" || exit $?

下記のようなエラーメッセージが出ます。
cp: '/tmp/mailman-migrate-from-fml.ksh.zLdXAmpV/*' を stat できません: そのよう なファイルやディレクトリはありません

**Comment by fumiyas** [comment]
Fixed.
